### PR TITLE
Add data hash calculation for MinAdaCalculator

### PR DESCRIPTION
**Pull request by somereason**
Add data hash calculation for MinAdaCalculator, according to https://github.com/input-output-hk/cardano-ledger/blob/master/doc/explanations/min-utxo-alonzo.rst

### CODE REVIEW

**Comment by satran004** [comment]
Thanks a lot for finding this gap and for the PR. 

Possible to add few tests with the datum hash scenarios mentioned in  (** WITH datum hash: **) section . Let me know

https://github.com/input-output-hk/cardano-ledger/blob/master/doc/explanations/min-utxo-alonzo.rst#example-min-ada-value-calculations-and-current-constants


Fyi, please ignore the test failure in CI. I will update that test after merge.

**Comment by satran004** [comment]
Merging this PR. Will add some tests after merge. Many thanks.

**Comment by somereason** [comment]
Sorry for the delay. I was stick with work. I'll do that later

**Comment by satran004** [comment]
No worries. Thanks for the help.

**Pull request merged**
